[package]
name = "h-cargo-crates"
version = "0.1.0"
edition = "2021"

[features]
add-numbers = []
multiply-numbers = []
manipulate-numbers = ["add-numbers", "multiply-numbers"]

default = ["manipulate-numbers"]